dist: xenial
language: python

python:
  - "3.7"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - pip install coverage
  - pip install codacy-coverage
  - pip install pytest-cov
  - pip install -r requirements.txt

script:
  - pytest --cov=divineoasis tests/

after_success:
  - coverage xml
  - python-codacy-coverage -r coverage.xml
