dist: xenial
language: python

python:
  - "3.7"

install:
  - pip install coverage
  - pip install codacy-coverage
  - pip install pytest-cov
  - pip install -r requirements.txt

script:
  - pytest --cov=divineoasis tests/

after_success:
  - coverage xml
  - python-codacy-coverage -r coverage.xml
