language: python

python:
  - "3.7"

install:
  - pip install coverage
  - pip install codacy-coverage
  - pip install -r requirements.txt

script:
  - coverage run -m divineoasis

after_success:
  - coverage xml
  - python-codacy-coverage -r coverage.xml
